title: DevML
description: DevML Workshop @ NeurIPS 2026

timezone: US/Eastern

navigation:
  Overview: "/devml"
  Schedule: "/devml/schedule"
  Speakers: "/devml/speakers"
  Organizers: "/devml/organizers"

markdown: kramdown

github:
  repository: https://bhavinc.github.io/devml/
kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
